#!/bin/bash

if [[ $# -ne 1 ]]; then
	echo "Usage: $0 <name of fruit>" >&2
	exit 1
fi

fruit="$1"

case "$fruit" in
	apple)
		echo "Red"
		;;
	banana)
		echo "Yellow"
		;;
	kiwi)
		echo "Green"
		;;
	*)
		echo "Unknown fruit: $fruit" >&2
		exit 1
		;;
esac
